openapi: 3.1.0
info:
  title: agent-states-api-v2 AccountSet Meta.json?top Count API
  version: '1.1'
servers:
- url: https://{instance}.response.lithium.com/api/v2/agentstate
  variables:
    instance:
      default: instance
security:
- {}
tags:
- name: Meta.json?top Count
paths:
  /{account}/{streamName}/meta.json?top_count:
    get:
      summary: Get tweets per period
      description: Number of tweets to include per period
      operationId: get-top-retweets-hourly-from-now
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
      - name: streamName
        in: path
        schema:
          type: string
        required: true
      - name: top_count
        in: query
        schema:
          type: integer
          format: int32
          default: 5
      responses:
        '200':
          description: '200'
          content:
            text/plain:
              examples:
                Result:
                  value: Coming Soon
      deprecated: false
      security: []
      tags:
      - Meta.json?top Count
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: false
x-readme-fauxas: true
