openapi: 3.2.0
info:
  title: agent-states-api-v2 AccountSet Meta.json?num Hours API
  version: '1.1'
servers:
- url: https://{instance}.response.lithium.com/api/v2/agentstate
  variables:
    instance:
      default: instance
security:
- {}
tags:
- name: Meta.json?num Hours
paths:
  /{account}/{streamName}/meta.json?num_hours:
    get:
      summary: Get hours of activity
      description: Retrieve the number of activity hours
      operationId: get-minutes-of-activity-1
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
      - name: streamName
        in: path
        schema:
          type: string
        required: true
      - name: num_hours
        in: query
        schema:
          type: integer
          format: int32
          default: 2
      responses:
        '200':
          description: '200'
          content:
            text/plain:
              examples:
                Result:
                  value: Coming Soon
      deprecated: false
      security: []
      tags:
      - Meta.json?num Hours
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: false
x-readme-fauxas: true
