openapi: 3.1.0
info:
  title: agent-states-api-v2 AccountSet Form API
  version: '1.1'
servers:
- url: https://{instance}.response.lithium.com/api/v2/agentstate
  variables:
    instance:
      default: instance
security:
- {}
tags:
- name: Form
paths:
  /form:
    post:
      summary: Send a bot response with a secure form
      description: Send a secure form as a bot response.
      operationId: send-a-bot-response-with-a-secure-form
      responses:
        '202':
          description: '202'
          content:
            application/json:
              examples:
                Result:
                  value: HTTP/1.1 202 Accepted
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl POST \\\n  https://api.app.lithium.com/bots/v3/form \\\n  --data @/path/to/payload.json \\\n  -H \"Content-type: application/json; charset=utf-8\" \\\n  -H \"Authorization: Bearer [TOKEN]\""
        samples-languages:
        - curl
      tags:
      - Form
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: false
x-readme-fauxas: true
