openapi: 3.1.0
info:
  title: agent-states-api-v2 AccountSet Changed API
  version: '1.1'
servers:
- url: https://{instance}.response.lithium.com/api/v2/agentstate
  variables:
    instance:
      default: instance
security:
- {}
tags:
- name: Changed
paths:
  /changed:
    get:
      summary: List author records changed today
      description: Get a list of author records that have changed in a 24-hour period
      operationId: authorschanged
      parameters:
      - name: startEpochMillis
        in: query
        description: The start time of the query period specified as milliseconds since the UNIX Epoch
        schema:
          type: integer
          format: int32
      - name: endEpochMillis
        in: query
        description: The end of of the query period specified as milliseconds since the UNIX Epoch
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{  \n  \"status\":\"success\",\n  \"data\":[  \n    \"2b1a0c87-d1c7-43bb-970c-6a7cdaf97ecd\",\n    \"20f6b1e8-ac3e-464b-9dd5-214ab6535aa1\",\n    \"a5cd888e-82b2-478d-a5ef-7352f3ac70c8\",\n    \"30823836-7a91-4fb2-a0ef-a0a0fe2d97fc\",\n    \"24e66ed6-6ac9-4110-84ab-e7f1ddeb7a7f\",\n    \"99c095b7-1bc0-4e30-a1c3-8dd7db520025\",\n    \"072fef63-6b81-4b9f-889d-ded192058f71\",\n    \"f7136383-cc61-4f58-9a38-68b3abcc0f21\",\n    \"95414533-7202-41a7-bbbb-b4c3bd587de4\",\n    \"33191153-bdd0-4618-85ba-ab1e06ffceba\",\n    \"bc1329d4-9b85-4afa-ad3f-bde2751c7e82\",\n    \"6ea89640-226e-11e9-83d2-0242ac110006\",\n    \"3b862966-64d9-4ba1-87b0-164aaa56e4be\",\n    \"145fc1b2-4b1a-4272-aea9-4580a1fa7034\",\n    \"f69c80b0-2ce7-11e9-bffb-0242ac110006\",\n    \"cc2804c7-c123-4d56-9629-66e392b54f76\",\n    \"630207c1-e58f-4098-aab6-658f63903669\",\n    \"c7e4deb7-29c0-4601-8348-b7b4d415ac5f\",\n    \"26de6eae-5bca-4015-825c-4d8602d4cc99\",\n    \"678f6e28-d92c-48d8-90ff-5375a8790f9e\",\n    \"2bde4007-b6c7-4d31-8a52-ad25b4c87ada\",\n    \"294ffa6f-5f1d-44e6-a5a0-5283c8462570\",\n    \"100ef826-4a82-4a93-8fd7-9c6c4cb8b2bd\",\n    \"73292839-fb73-4b2c-b7b6-32db4b2f855a\",\n    \"6a6c1936-0b57-475e-b1f9-2276d3b784ec\",\n    \"37ba7f8a-af0a-404c-bfa2-1f625b0b484e\",\n    \"a508eba0-28f3-11e9-add0-0242ac110004\",\n    \"30e3fe36-a970-451f-a479-2cc47ad1b9a0\",\n    \"8896205e-4777-42f5-bdb3-80bf4aa18b16\",\n    \"129381ed-4e24-4757-a4ba-81bfc881468d\",\n    \"3100aec4-fe37-4b4c-9768-a4b1b5c3ebf0\",\n    \"a4921959-5b88-423d-848a-7a2710623538\",\n    \"630207c1-e58f-4098-aab6-658f63903669\",\n    \"9b749c34-7a58-4979-9637-234783b9db32\"\n  ]\n}\n"
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: string
                      example: 2b1a0c87-d1c7-43bb-970c-6a7cdaf97ecd
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      security: []
      x-readme:
        code-samples:
        - language: curl
          code: curl -L -u [USERNAME]:[PASSWORD] 'https://your_social_response_intance.lithium.com/api/v2/authors/changed'
        samples-languages:
        - curl
      tags:
      - Changed
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: false
x-readme-fauxas: true
