openapi: 3.2.0
info:
  title: agent-states-api-v2 AccountSet Email API
  version: '1.1'
servers:
- url: https://{instance}.response.lithium.com/api/v2/agentstate
  variables:
    instance:
      default: instance
security:
- {}
tags:
- name: Email
paths:
  /email/{userEmail}/state:
    put:
      summary: Set Agent State by Email
      description: Change the State (`stateUUID`) of an Agent identified by Email (`userEmail`)
      operationId: change-agent-state-by-email
      parameters:
      - name: stateUUID
        in: query
        description: The unique identifier for the state to which the Agent will be switched.
        schema:
          type: string
      - name: userEmail
        in: path
        description: The email address of the agent being placed into a new state.
        schema:
          type: string
        required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": \"success\",\n    \"data\": \"OK\"\n}"
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: string
                    example: OK
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": \"fail\",\n    \"message\": \"State with UUID c0ed7f9f-f98a-40a8-a9a4-example56ba8 not available to team TEAM.5228 for User 1234567<name@example.com / John Doe> with user UUID example-7eef-4196-ad76-cb2f2ebbdd03\"\n}"
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: State with UUID c0ed7f9f-f98a-40a8-a9a4-example56ba8 not available to team TEAM.5228 for User 1234567<name@example.com / John Doe> with user UUID example-7eef-4196-ad76-cb2f2ebbdd03
        '500':
          description: '500'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": \"fail\",\n    \"message\": \"User 1234567<name@example.com / John Doe> with user UUID example-7eef-4196-ad76-cb2f2ebbdd03 does not have an active session, could not set state to example-5c3e-4c2f-8949-670425bb4e18\"\n}"
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: User 1234567<name@example.com / John Doe> with user UUID example-7eef-4196-ad76-cb2f2ebbdd03 does not have an active session, could not set state to example-5c3e-4c2f-8949-670425bb4e18
      deprecated: false
      security: []
      x-readme:
        code-samples:
        - language: curl
          code: curl -L -u username:password 'https://{care-instance}/api/v2/users/email/example@example.com/state?stateUUID=677af682-c4dd-4add-9a83-example'
        samples-languages:
        - curl
      tags:
      - Email
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: false
x-readme-fauxas: true
